# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx

      - name: Login into Github Docker Registery
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u shyim --password-stdin
        
      - name: Build image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --tag ghcr.io/shyim/gnu-libiconv:v3.14 --push .
